# helm/templates/chatbot-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
      annotations:
        fluentd.io/tag: kubernetes.chatbot
    spec:
      containers:
        - name: chatbot
          image: "{{ .Values.images.chatbot.repository }}-{{ .Values.environment }}:{{ .Values.version }}"
          ports:
            - containerPort: 8501
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: OPENAI_API_KEY
            - name: SENTIMENT_API_BASE_URL
              value: "{{ .Values.env.SENTIMENT_API_BASE_URL }}"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /var/log/containers
              name: varlogcontainers
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
      volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers