---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-master-elasticsearch-master-0
  namespace: logging
  labels:
    app: elasticsearch-master
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: albert-shoes-shop-chatbot
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-master-elasticsearch-master-1
  namespace: logging
  labels:
    app: elasticsearch-master
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: albert-shoes-shop-chatbot
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-master-elasticsearch-master-2
  namespace: logging
  labels:
    app: elasticsearch-master
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: albert-shoes-shop-chatbot
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi
