apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.env.OPENAI_API_KEY | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.env.AWS_ACCESS_KEY_ID | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.env.AWS_SECRET_ACCESS_KEY | b64enc | quote }}