# helm/templates/sentiment-analysis-api-hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sentiment-analysis-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sentiment-analysis-api
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80