# helm/kibana/values.yaml
elasticsearchHosts: "http://elasticsearch-master:9200"
replicas: 1
service:
  type: LoadBalancer
  port: 5601
resources:
  requests:
    cpu: "100m"
    memory: "1Gi"
  limits:
    cpu: "500m"
    memory: "2Gi"
livenessProbe:
  httpGet:
    path: /healthz
    port: 5000
  initialDelaySeconds: 30
  timeoutSeconds: 10
readinessProbe:
  httpGet:
    path: /healthz
    port: 5000
  initialDelaySeconds: 30
  timeoutSeconds: 10

livenessProbeAppB:
  httpGet:
    path: /healthz
    port: 8051
  initialDelaySeconds: 30
  timeoutSeconds: 10
readinessProbeAppB:
  httpGet:
    path: /healthz
    port: 8051
  initialDelaySeconds: 30
  timeoutSeconds: 10
