apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot
          image: 255945442255.dkr.ecr.us-east-1.amazonaws.com/ce5-group6-ecr-chatbot:latest
          # TODO: Use the correct image tag (from values.yaml)
          ports:
            - containerPort: 8501
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: OPENAI_API_KEY
            - name: SENTIMENT_ANALYSIS_API
              value: "http://sentiment-analysis-api-service"