apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-analysis-api
  template:
    metadata:
      labels:
        app: sentiment-analysis-api
    spec:
      containers:
        - name: sentiment-analysis-api
          image: 255945442255.dkr.ecr.us-east-1.amazonaws.com/ce5-group6-ecr:sentiment-analysis-api-latest
          ports:
            - containerPort: 5000