apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-analysis-api
  template:
    metadata:
      labels:
        app: sentiment-analysis-api
    spec:
      containers:
        - name: sentiment-analysis-api
          image: 255945442255.dkr.ecr.us-east-1.amazonaws.com/ce5-group6-ecr-api:latest
          # TODO: Use the correct image tag (from values.yaml)
          ports:
            - containerPort: 5000
          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: DYNAMODB_TABLE_NAME
              value: "ce5-group6-user-queries"
            - name: LOGGING_LEVEL
              value: "20"
            # 10 = DEBUG, 20 = INFO, 30 = WARNING, 40 = ERROR, 50 = CRITICAL
            - name: DEBUG
              value: "False"
            # Enable debug mode. "True" or "False"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-key-id
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-access-key
                  key: AWS_SECRET_ACCESS_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: OPENAI_API_KEY
